title: CARL IR docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://neltanner.github.io/new-repository-libs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
